# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class {{ .FormulaName }} < Formula
  desc "{{ .Description }}"
  homepage "https://Indobase.com"
  version "{{ .Version }}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Indobase/cli/releases/download/v{{ .Version }}/Indobase_darwin_arm64.tar.gz"
      sha256 "{{ .Checksum.Indobase_darwin_arm64 }}"

      def install
        bin.install "Indobase"
        (bash_completion/"Indobase").write `#{bin}/Indobase completion bash`
        (fish_completion/"Indobase.fish").write `#{bin}/Indobase completion fish`
        (zsh_completion/"_Indobase").write `#{bin}/Indobase completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Indobase/cli/releases/download/v{{ .Version }}/Indobase_darwin_amd64.tar.gz"
      sha256 "{{ .Checksum.Indobase_darwin_amd64 }}"

      def install
        bin.install "Indobase"
        (bash_completion/"Indobase").write `#{bin}/Indobase completion bash`
        (fish_completion/"Indobase.fish").write `#{bin}/Indobase completion fish`
        (zsh_completion/"_Indobase").write `#{bin}/Indobase completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Indobase/cli/releases/download/v{{ .Version }}/Indobase_linux_arm64.tar.gz"
      sha256 "{{ .Checksum.Indobase_linux_arm64 }}"

      def install
        bin.install "Indobase"
        (bash_completion/"Indobase").write `#{bin}/Indobase completion bash`
        (fish_completion/"Indobase.fish").write `#{bin}/Indobase completion fish`
        (zsh_completion/"_Indobase").write `#{bin}/Indobase completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Indobase/cli/releases/download/v{{ .Version }}/Indobase_linux_amd64.tar.gz"
      sha256 "{{ .Checksum.Indobase_linux_amd64 }}"

      def install
        bin.install "Indobase"
        (bash_completion/"Indobase").write `#{bin}/Indobase completion bash`
        (fish_completion/"Indobase.fish").write `#{bin}/Indobase completion fish`
        (zsh_completion/"_Indobase").write `#{bin}/Indobase completion zsh`
      end
    end
  end
end

